name: Daily Instagram DM Check

on:
  schedule:
    # Runs at 23:00 UTC every day
    - cron: '0 23 * * *'
  workflow_dispatch: # Allows manual trigger from GitHub UI

jobs:
  check-dms:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Change to dawg-bot directory
      run: cd dawg-bot
    
    - name: Cache last run file
      uses: actions/cache@v3
      with:
        path: dawg-bot/.last-run
        key: last-run-${{ github.run_number }}
        restore-keys: |
          last-run-
    
    - name: Random delay (0-59 minutes)
      run: |
        DELAY=$((RANDOM % 3600))
        echo "Waiting $DELAY seconds ($(($DELAY / 60)) minutes) for random timing..."
        sleep $DELAY
    
    - name: Install dependencies
      run: |
        cd dawg-bot
        npm install
    
    - name: Check Instagram DMs
      env:
        INSTAGRAM_USERNAME: ${{ secrets.INSTAGRAM_USERNAME }}
        INSTAGRAM_PASSWORD: ${{ secrets.INSTAGRAM_PASSWORD }}
        INSTAGRAM_USERID: ${{ secrets.INSTAGRAM_USERID }}
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      run: |
        cd dawg-bot
        node simple-dm-reader.js
    
    - name: Save last run file
      if: always()
      uses: actions/cache/save@v3
      with:
        path: dawg-bot/.last-run
        key: last-run-${{ github.run_number }}